---
apiVersion: v1
kind: Service
metadata:
  name: pg-pgb
  labels:
    app: pg-pgb
    app.kubernetes.io/part-of: pgbouncer-poc
spec:
  selector:
    app: pg-pgb
  ports:
    - name: database
      port: 5432
      targetPort: 5432
